name: chat_app
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.6.1


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_login: ^5.0.0
  firebase_auth: ^5.5.2
  firebase_core: ^3.13.0
  flutter_spinkit: ^5.2.1
  google_sign_in: ^6.3.0
  provider: ^6.1.5
  cloud_firestore: ^5.6.6
  font_awesome_flutter: ^10.8.0
  image_picker: ^1.1.2
  shared_preferences: ^2.5.3
  firebase_messaging: ^15.2.5
  firebase_storage: ^12.4.5
  circular_profile_avatar: ^2.0.5
  popover: ^0.3.1
  intl: ^0.20.2
  custom_refresh_indicator: ^4.0.1
  emoji_picker_flutter: ^4.3.0
  animations: ^2.0.11
  flutter_slidable: ^4.0.0
  go_router: ^15.1.3
  http: ^1.4.0
  rxdart: ^0.28.0
  app_settings: ^6.1.1
  permission_handler: ^12.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^5.0.0


flutter:

  
  uses-material-design: true

  assets:
    - assets/


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
