// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXFUNRPqHoscgpmLZQU2UWh2cqVcW_tSE',
    appId: '1:497192567245:web:e857dedb3a79c4371dc484',
    messagingSenderId: '497192567245',
    projectId: 'chat-app-14e27',
    authDomain: 'chat-app-14e27.firebaseapp.com',
    storageBucket: 'chat-app-14e27.firebasestorage.app',
    measurementId: 'G-Q99MY0BJ9B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjqyiVLwvC86eOvgg-Z81lsjSnb-RytxM',
    appId: '1:497192567245:android:aea1a0ab9c922d631dc484',
    messagingSenderId: '497192567245',
    projectId: 'chat-app-14e27',
    storageBucket: 'chat-app-14e27.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5FKyDbE8PRMNvmlJHjYWicruf6WNuTiY',
    appId: '1:497192567245:ios:7d20d229ee62b9611dc484',
    messagingSenderId: '497192567245',
    projectId: 'chat-app-14e27',
    storageBucket: 'chat-app-14e27.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5FKyDbE8PRMNvmlJHjYWicruf6WNuTiY',
    appId: '1:497192567245:ios:7d20d229ee62b9611dc484',
    messagingSenderId: '497192567245',
    projectId: 'chat-app-14e27',
    storageBucket: 'chat-app-14e27.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );
}
